
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: ptpconfig-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: ptpconfig-validator-webhook-service
      namespace: system
      path: /validate-ptp-openshift-io-v1-ptpconfig
  failurePolicy: Fail
  name: ptpconfigvalidationwebhook.openshift.io
  rules:
  - apiGroups:
    - ptp.openshift.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ptpconfigs
  sideEffects: None
